version: '3.3'
services:
  hue_routines:
    build: ./
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "2"
    command: python3 /app/hue_routines_main.py